name: PyPI release

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.ref }}
        env: 
          REF: ${{ github.event.ref }}
        run: echo "Commit $REF"
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U setuptools wheel twine
      
      - name: Build the dist files
        run: python setup.py bdist_wheel && python setup.py sdist
      
      - name: Publish to the test PyPI
        env:
          TWINE_USERNAME: ${{ secrets.TEST_PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD }}
        run: twine upload dist/* -r pypitest --repository-url=https://test.pypi.org/legacy/    

      - name: Test installing diffusers and importing
        run: |
          pip install blossoms_sayak && pip uninstall blossoms_sayak -y
          pip install -i https://testpypi.python.org/pypi blossoms_sayak
          python -c "from blossoms_sayak import __version__; print(__version__)"
          python -c "from blossoms_sayak import *"

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: twine upload dist/* -r pypi